// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdPxH6hPCu_yxfTTrNAYS3gtI7ldcRJBU',
    appId: '1:815041198538:web:4eb9c0492094f249f0b733',
    messagingSenderId: '815041198538',
    projectId: 'gerenciador-de-tarefas-59f3a',
    authDomain: 'gerenciador-de-tarefas-59f3a.firebaseapp.com',
    storageBucket: 'gerenciador-de-tarefas-59f3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNMPTU8Tre0yIhCLqIyuIQ4qWzxC6sWo',
    appId: '1:815041198538:android:aa898326b3b77ac2f0b733',
    messagingSenderId: '815041198538',
    projectId: 'gerenciador-de-tarefas-59f3a',
    storageBucket: 'gerenciador-de-tarefas-59f3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxRuZP1A8RwwfrXkinVy5j66FG8kWa9KU',
    appId: '1:815041198538:ios:cd5f7fa499e5c0e2f0b733',
    messagingSenderId: '815041198538',
    projectId: 'gerenciador-de-tarefas-59f3a',
    storageBucket: 'gerenciador-de-tarefas-59f3a.firebasestorage.app',
    iosBundleId: 'com.example.gerenciadorTarefas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdPxH6hPCu_yxfTTrNAYS3gtI7ldcRJBU',
    appId: '1:815041198538:web:e10ede4689e27c62f0b733',
    messagingSenderId: '815041198538',
    projectId: 'gerenciador-de-tarefas-59f3a',
    authDomain: 'gerenciador-de-tarefas-59f3a.firebaseapp.com',
    storageBucket: 'gerenciador-de-tarefas-59f3a.firebasestorage.app',
  );
}
